[SddmTheme]
Name=stellarium
Description=Lockscreen for surface-dots
Type=sddm-theme
Author=snes
Version=1.0
MainScript=Main.qml
ConfigFile=theme.conf

[General]
background=assets/wall-earth.jpg
defaultBackground=assets/wall-earth.jpg
accent=#61886a
